### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [mypachec/prj-rev-bwfs-dasmoto#6]
https://github.com/mypachec/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/Resources/CSS/style.css#L1-L6

If enough elements are using a certain style, considering making that a default style by using the universal selector `*`. 

```css
* {
  font-family: Helvetica;
}
```
